### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DanielOaks** [neynt/tsundiary#11]
Hi @neynt!

If you could choose a license for this project, it would be very much appreciated. I want to do some work on this, but I'm wondering what sort of license it'd be under before I get too far into it.

I'm hoping something simple like the [ISC](http://choosealicense.com/licenses/isc/), [MIT](http://choosealicense.com/licenses/mit/), or something similar, but whatever you think is best.

**Comment by neynt** [comment]
Hi @DanielOaks! Sorry about the delayed response. I've been busy with an internship and haven't been checking GitHub too often.

It's super sweet that you want to work on this! I put this whole thing under the MIT license, so feel free to have at it.

**Comment by DanielOaks** [comment]
All good, hope the intership's going well!

Thanks a bunch for the MIT license, it's much appreciated. I'll do my best!
